spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///test?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
mybatis:
  config-location: classpath:mybatis/mybatis_config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
